### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by xiaofeihe** [stuxuhai/HData#2]
`
 sudo  ./bin/package-hdata.sh
[sudo] sen 的密码： 
./bin/package-hdata.sh: 行 34: mvn: 未找到命令
cp: 无法获取"/home/sen/dev/HData/hdata-core/target/hdata-core-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-core/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-api/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-console/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-console/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-csv/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-csv/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-excel/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-excel/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-ftp/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-ftp/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-hbase/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-hbase/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-hdfs/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-hdfs/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-hive/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-hive/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-http/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-http/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-jdbc/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-jdbc/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-kafka/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-kafka/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-mongodb/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sen/dev/HData/hdata-mongodb/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录

`

**Comment by stuxuhai** [comment]
./bin/package-hdata.sh: 行 34: mvn: 未找到命令

不是不没有安装maven

**Comment by TimeIsGoOn** [comment]
求助
```

➜  HData git:(master) ✗ ./bin/package-hdata.sh
./bin/package-hdata.sh: 行 34: mvn: 未找到命令
cp: 无法获取"/home/sun/learn/HData/hdata-core/target/hdata-core-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-core/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-api/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-console/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-console/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-csv/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-csv/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-excel/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-excel/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-ftp/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-ftp/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-hbase/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-hbase/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-hdfs/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-hdfs/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-hive/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-hive/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-http/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-http/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-jdbc/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-jdbc/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-kafka/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-kafka/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-mongodb/target/hdata-*.jar" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/sun/learn/HData/hdata-mongodb/target/dependency/*.jar" 的文件状态(stat): 没有那个文件或目录

```

**Comment by stuxuhai** [comment]
@TimeIsGoOn 没有安装maven吧

**Comment by xiaofeihe** [comment]
安装了 maven3  再翻墙 后，编译成果
