### ISSUE TITLE
HBase：如果抽数时，region个数发生了变化怎么处理？

### ISSUE THREAD

**Issue by dlnufox** [stuxuhai/HData#20]
HBase：如果抽数时，region个数发生了变化怎么处理？

重点是抽数的结果还正确吗？

**Comment by stuxuhai** [comment]
变化的region不会抽取，hdata只处理启动时刻的region

**Comment by dlnufox** [comment]
假设plugin已经得到 A B C D E 共 5 个 region

如果当抽取 region B 时，region C 被拆成了 C1、C2 两个 region，请问原来 region C 中的数据怎么处理的？

**Comment by stuxuhai** [comment]
获取的是每个region的startkey和endkey，当region拆分时startkey和endkey并没变化，具体代码如下：

``` java
Connection conn = ConnectionFactory.createConnection(conf);
RegionLocator regionLocator = conn.getRegionLocator(tableName);
Pair<byte[][], byte[][]> startEndKeysPair = regionLocator.getStartEndKeys();
```

**Comment by dlnufox** [comment]
明白了，谢谢！
