### ISSUE TITLE
SimpleDateFormat 并不是线程安全的

### ISSUE THREAD

**Issue by zqq90** [stuxuhai/HData#25]
```
 * Formats are generally not synchronized.
 * It is recommended to create separate format instances for each thread.
 * If multiple threads access a format concurrently, it must be synchronized
 * externally.
```

这里使用 `SimpleDateFormat.format(..)` 可能会有些问题

https://github.com/stuxuhai/HData/blob/v0.2.8/hdata-jdbc/src/main/java/com/github/stuxuhai/hdata/plugin/writer/jdbc/JDBCWriter.java#L37
https://github.com/stuxuhai/HData/blob/v0.2.8/hdata-jdbc/src/main/java/com/github/stuxuhai/hdata/plugin/writer/jdbc/JDBCWriter.java#L109

**Comment by zqq90** [comment]
其他地方也陆续发现了同样的问题, 或许可以写一个 Util 来统一处理

**Comment by dogHere** [comment]
@zqq90 这个地方是在线程内跑的，不存在竞争问题。
