### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by fight-lyk** [stuxuhai/HData#29]
请问一下，这个编译了，运行E:\GraduateDeign\git\HData\build\hdata\bin>hdata job.xml
或者hdata -f job.xml，都出现：错误: 找不到或无法加载主类 com.github.stuxuhai.hdata.CliDriver
这是怎么情况，我的xml很简单的，
<？xml version = “ 1.0 ” encoding = “ UTF-8 ”？> 
< job  id = “ job_example ” > 
    < reader  name = “ jdbc ” > 
		< url > jdbc:mysql://127.0.0.1:3306/work?useUnicode=true&characterEncoding=utf8 </ url > 
		< driver > com.mysql.jdbc.Driver </ driver > 
		< user > root </ user > 
		< password >  </ password > 
		< table > img_url </ table > 
	< writer  name = “ csv ” > 
		< path > E:\GraduateDeign\git\HData\build\demo.csv </ path > 
xml应该没问题的，谢谢啊！

**Comment by fight-lyk** [comment]
懂了，好像没安装maven，先去安了试试

**Comment by fight-lyk** [comment]
安装了maven，重新编译应该成功了，但运行是还是出现错误: 找不到或无法加载主类 com.github.stuxuhai.hdata.CliDriver，这个是怎么回事

**Comment by zqq90** [comment]
@fight-lyk , 在 `build` 文件夹下面找到压缩包, 解压到一个位置, 执行那里面的 `hdata`

**Comment by fight-lyk** [comment]
我是那么弄的，我用package-hdata.bat编译，出来个zip的压缩包，我就在build下解压，然后去运行hdata，
（我编译解压后文件大小就不到4kb，我怀疑编译出错了，但又不知道错哪，我已经安装了maven了的）
结果就报错错误: 找不到或无法加载主类 com.github.stuxuhai.hdata.CliDriver

**Comment by fight-lyk** [comment]
是编译错了，我在看一会

**Comment by fight-lyk** [comment]
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.249 s
[INFO] Finished at: 2017-04-14T11:18:54+08:00
[INFO] Final Memory: 5M/15M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "copy-dependency" could not be activated because it does not exist.
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (E:\GraduateDeign\git\HData\bin). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
cp: cannot stat '/e/GraduateDeign/git/HData/hdata-core/target/hdata-core-*.jar': No such file or directory
cp: cannot
这个是什么错误，求大神指点.

**Comment by fight-lyk** [comment]
弄不出来，不弄了。本来这个项目文件格式转换应该可以属于数据预处理的一部分，如果在转换过程中加上其他的一些数据处理方法就完美了。但发现连编译都不成功，其他的就不可能实现了。

**Comment by dogHere** [comment]
你在错误的位置执行了mvn，建议花5分钟看一下mvn是什么，耐心点就会好。

"转换过程中加上其他的一些数据处理方法"确实很好，实现一个map和filter应该不难。
