### ISSUE TITLE
如果同步的数据太多,如何连续的进行同步操作

### ISSUE THREAD

**Issue by TimeIsGoOn** [stuxuhai/HData#3]
我遇到个情况是对方数据量很大,4千万条数据,并且每天还要持续的写入400万条.
这种情况的话如何处理呢?

**Comment by stuxuhai** [comment]
需要实时同步的吗？

**Comment by TimeIsGoOn** [comment]
感谢,不需要实时,每10分钟同步一次就可以.但是第一次同步的时候数据量很大.我们业务同步的数据每条记录都是有时间的,格式为 Y-m-d H:i:s,

**Comment by stuxuhai** [comment]
第一次先全量导入(适当提高并行度已提高导入效率)，记下截止时间，然后后面可以根据时间采用增量导入

**Comment by TimeIsGoOn** [comment]
你好,比如对方是oracle数据库表A,我是mysql数据库表B,我要把A的数据同步到B里面,如果是开多进程写入表B的话,不就会造成锁表了吗?等同于一个进程一个一个的写入 . 你说的并行导入我没听懂

**Comment by stuxuhai** [comment]
如果是这样的话可以把reader的并行度调大一点，hdata会根据读表的主键id进行分片读取，比如设置reader的并行度为5(即-Rparallelism=5，相当于5个线程并行读取)，首先hdata会根据查询条件查找max(id)和min(id)，然后根据id的区间范围均匀地分为5份，每个线程负责读取一份区间的数据。

**Comment by TimeIsGoOn** [comment]
感谢您的回复,不过我困惑的是读取过来之后是放到哪里了呢?是先统一放到redis里面,然后在从redis导入到mysql里面?(我的这个情景中),这个对内存的要求挺高吧,比如我数据是5个G的话,内存4G就不行了.
我的理解是你是想要把数据快速的都写到队列里面,然后出队列写入mysql.我这么理解正确吗?

**Comment by stuxuhai** [comment]
放在内存中，hdata使用了缓冲区，并不是说5G的数据就需要5G的内存空间
